preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  google:
  maven-central:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 1.9.10
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version-ref: kotlin-jvm
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: 1.5.1
  com.android.application:
    alias: android-application
    version: 8.1.1
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.25.3

libraries:
  androidx.compose:
    compose-bom:
      version: 2023.09.02
  androidx.compose.foundation:
    foundation:
      version: <no-spec>
  androidx.compose.ui:
    ui:
      version: <no-spec>
  androidx.compose.material3:
    material3:
      version: <no-spec>
  androidx.activity:
    activity-compose:
      version: 1.7.2
  androidx.core:
    core-ktx:
      version: 1.10.0
  androidx.appcompat:
    appcompat:
      version: 1.6.1
  com.google.android.material:
    material:
      version: 1.8.0
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1
  junit:
    junit:
      version: 4.13.2