preferences:
  autowire-on-sync-mode: UPDATE_OPTIONAL_DEPENDENCIES
  repositories-mode: FAIL_ON_PROJECT_REPOS

repositories:
  gradle-plugin-portal:
    scope: PLUGINS
  maven-local:
  google-aliyun:
      url: https://maven.aliyun.com/repository/google/
  maven-central-aliyun:
      url: https://maven.aliyun.com/repository/central/
  jit-pack-aliyun:
      url: https://maven.aliyun.com/repository/jcenter/
  google:
  maven-central:
  jit-pack:

plugins:
  org.jetbrains.kotlin.jvm:
    alias: kotlin-jvm
    version: 2.0.0
  org.jetbrains.kotlin.android:
    alias: kotlin-android
    version-ref: kotlin-jvm
  org.jetbrains.kotlin.plugin.compose:
    alias: kotlin-compose
    version-ref: kotlin-jvm
  org.jetbrains.compose:
    alias: jetbrains-compose
    version: 1.6.11
  com.android.application:
    alias: android-application
    version: 8.5.0
  com.vanniktech.maven.publish:
    alias: maven-publish
    version: 0.28.0

libraries:
  org.jetbrains.kotlin:
    kotlin-reflect:
      version-ref: <plugins>::kotlin-jvm
  androidx.compose:
    compose-bom:
      version: 2024.06.00
  androidx.compose.foundation:
    foundation:
      version: <no-spec>
  androidx.compose.ui:
    ui:
      version: <no-spec>
  androidx.compose.material3:
    material3:
      version: <no-spec>
  androidx.activity:
    activity-compose:
      version: 1.9.0
  androidx.core:
    core-ktx:
      version: 1.13.1
  androidx.appcompat:
    appcompat:
      version: 1.7.0
  com.google.android.material:
    material:
      version: 1.12.0
  androidx.test.ext:
    junit:
      version: 1.1.5
  androidx.test.espresso:
    espresso-core:
      version: 3.5.1
  junit:
    junit:
      version: 4.13.2